name: 'Test all modules'

on:
  push:
    branches: [ main ]
    paths:
      - femutils/**
  pull_request:
    branches: [ main ]
    paths:
      - femutils/**
  workflow_dispatch:

env:

  SOURCE_DIR: '/__w/arcanefem/arcanefem/src'
  BUILD_DIR: '/__w/arcanefem/arcanefem/build'

  # CTest
  CT_RESULT_DIR: '/__w/arcanefem/arcanefem/test'
  CT_OPTS: "--timeout 300 --output-on-failure"

  # MPI
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  OMPI_MCA_rmaps_base_oversubscribe: 1

jobs:
  tests:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/arcaneframework/arcane_ubuntu-2204:gcc-12_full_check_latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: ${{ env.SOURCE_DIR }}

      - name: Configure
        shell: bash
        run: |
          cmake \
          -S ${{ env.SOURCE_DIR }} \
          -B ${{ env.BUILD_DIR }} \
          -GNinja

      - name: Build
        shell: bash
        run: |
          cmake --build ${{ env.BUILD_DIR }}

      - name: Test
        shell: bash
        run: |
          mkdir -p ${{ env.CT_RESULT_DIR }}
          ctest --test-dir ${{ env.BUILD_DIR }} --output-junit ${{ env.CT_RESULT_DIR }}/results.xml ${{ env.CT_OPTS }}

      - name: Upload test artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-all-modules-artifact
          path: ${{ env.CT_RESULT_DIR }}
          retention-days: 7